### ISSUE TITLE
Update Arizona header once off-canvas markup is finalized.

### ISSUE THREAD

**Issue by trackleft** [az-digital/arizona-bootstrap#213] opened 2021-01-08 21:45 UTC
Update [Arizona Header](https://github.com/az-digital/arizona-bootstrap/blob/main/site/docs/2.0/components/arizona-header.md) with new search and menu open buttons for mobile once they are finalized. Use the same markup for both.

_Originally posted by @trackleft in https://github.com/az-digital/arizona-bootstrap/pull/209#discussion_r554201634_

**Requirements:**
- Markup on AZ Barrio should match Arizona Bootstrap (reduce extra markup as much as possible)
    - Update main menu template
- Address scrolling issues on menu (should scroll) and background (should not scroll https://github.com/az-digital/az_quickstart/issues/614)

**Potential future ticket:**
- Implement menu with modal component instead of collapse component (see BS5)

**Comment by akslay** [comment] 2021-03-23 15:24
@trackleft Do you know if this has already been addressed/resolved by other pull requests (i.e., #566) ? The markup for the offcanvas nav and Arizona Header appear to be the same as what we have in Bootstrap.

> Markup on AZ Barrio should match Arizona Bootstrap (reduce extra markup as much as possible. Update main menu template

**Comment by akslay** [comment] 2021-03-25 22:33
Did a little bit of investigation, and it looks like the Arizona Header tasks are already complete (markup matches). On the Drupal side, however, you still cannot scroll when the mobile nav extends past the side of the screen fold. This is not an issue in AZ Bootstrap (works fine in the documentation) so a separate issue needs to be opened/fixed on the AZ Quickstart side.

The issue of resolving background scroll while you are scrolling through the mobile nav should be a separate issue as well, since it's unrelated to the Arizona Header markup and would be an independent improvement to the off-canvas mobile nav. Not sure if we want to "morph" this ticket into addressing that scrolling issue, or if we want to create a fresh issue.

**Comment by danahertzberg** [comment] 2021-03-25 23:01
@akslay Let's keep this ticket for the menu scrolling issue. I will create a separate issue for the GA release for the background scroll issue.

**Comment by akslay** [comment] 2021-03-25 23:19
> Let's keep this ticket for the menu scrolling issue. I will create a separate issue for the GA release for the background scroll issue.

I think we actually need a separate issue for the menu scrolling not working, because the issue isn't in Arizona Bootstrap, it's in AZ Quickstart. So the fix would be in the CSS of the `az_quickstart` repo rather than the `arizona_bootstrap` repo. Did you want to keep this ticket for the background scroll instead?

**Comment by danahertzberg** [comment] 2021-03-25 23:28
@akslay I'll just create a new one for az_quickstart. I already made one for the background scroll issue.

**Comment by akslay** [comment] 2021-04-02 18:07
- [x] Update Arizona Header with new search and menu open buttons for mobile once they are finalized. Use the same markup for both.
- [x] Markup on AZ Barrio should match Arizona Bootstrap (reduce extra markup as much as possible)
- [x] Update main menu template


All of the above items have already been completed in other PRs/issues. Only task that remains for this ticket is the background scroll while offcanvas menu is open.
- [ ] Address scrolling issues on menu (should scroll) and background

**Closed** 2021-04-07 20:55 UTC
Labels: enhancement
