### ISSUE TITLE
Active state on buttons in header issue

### ISSUE THREAD

**Issue by danahertzberg** [az-digital/arizona-bootstrap#244] opened 2021-03-10 20:15 UTC
_SASG found original bug_

Menu items styled like buttons in the header have light gray backgrounds when active

![image.png](https://images.zenhubusercontent.com/5eb9d10a2b1f2c51836b60e3/5ed630ef-93fd-46a0-b031-f0334cad2cae)

**Comment by joeparsons** [comment] 2024-07-10 21:18
Going to close this as a duplicate of #609 so we can fix button related issues together.  Feel free to re-open if needed.

**Closed by joeparsons** 2024-07-10 21:18 UTC
Labels: bug
