### ISSUE TITLE
Add az-vimeo icon to bootstrap docs.

### ISSUE THREAD

**Issue by trackleft** [az-digital/arizona-bootstrap#457] opened 2022-04-07 21:26 UTC
## Conditions of satisfaction
- [ ] vimeo icon should be here: https://digital.arizona.edu/arizona-bootstrap/docs/2.0/icons/

**Comment by michaelhagedon** [comment] 2022-04-07 21:35
Oh yeah, good call -- I thought about this during az-digital/az-icons#17, but then forgot!

**Comment by joeparsons** [comment] 2024-07-10 21:56
Closing this as a duplicate of #1153

**Closed by joeparsons** 2024-07-10 21:56 UTC
